"""
app/utils/safety.py  –  Allowlist-based safety layer for all DB operations.

Rules
-----
- Never allow destructive operations: delete_many, drop, deleteMany …
- Only find / aggregate / limited update pass through
- Query strings (generated by LLM) are scrubbed before execution
"""
from __future__ import annotations

import re
from typing import Any

BLOCKED_OPERATORS: frozenset[str] = frozenset(
    {
        "$where",          # arbitrary JS execution
    }
)

BLOCKED_KEYWORDS_RE = re.compile(
    r"\b(delete_many|deleteMany|drop_collection|drop_database"
    r"|dropCollection|dropDatabase|drop|remove|eval|mapReduce"
    r"|system\.js|shutdown|fsync)\b",
    re.IGNORECASE,
)

ALLOWED_TOP_LEVEL_PIPELINE_STAGES = frozenset(
    {
        "$match", "$group", "$sort", "$limit", "$skip",
        "$project", "$unwind", "$lookup", "$count",
        "$addFields", "$replaceRoot", "$facet", "$bucket",
        "$bucketAuto", "$sortByCount", "$sample",
    }
)


class SafetyError(Exception):
    """Raised when a query or operation violates safety rules."""


def validate_filter(query_filter: dict[str, Any]) -> None:
    """Recursively verify no blocked operators exist in a filter dict."""
    for key, value in query_filter.items():
        if key in BLOCKED_OPERATORS:
            raise SafetyError(f"Blocked operator detected: {key!r}")
        if isinstance(value, dict):
            validate_filter(value)
        elif isinstance(value, list):
            for item in value:
                if isinstance(item, dict):
                    validate_filter(item)


def validate_pipeline(pipeline: list[dict[str, Any]]) -> None:
    """Validate an aggregation pipeline."""
    for stage in pipeline:
        for stage_key in stage.keys():
            if stage_key not in ALLOWED_TOP_LEVEL_PIPELINE_STAGES:
                raise SafetyError(
                    f"Aggregation stage {stage_key!r} is not in the allowlist."
                )
            # Recursively check inner filter docs
            if isinstance(stage.get(stage_key), dict):
                validate_filter(stage[stage_key])


def validate_raw_string(text: str) -> None:
    """Scan a raw query string (LLM output) for dangerous patterns."""
    if BLOCKED_KEYWORDS_RE.search(text):
        match = BLOCKED_KEYWORDS_RE.search(text)
        raise SafetyError(
            f"Potentially destructive keyword detected: {match.group()!r}"
        )


def sanitize_projection(projection: dict[str, Any] | None) -> dict[str, Any] | None:
    """Remove any attempts to project system fields."""
    if projection is None:
        return None
    return {k: v for k, v in projection.items() if not k.startswith("__")}
